----------------------------------------------------

CREATE TABLE PROYECTODB.TBL_PACIENTES
(
    ID_PACIENTE NUMBER NOT NULL,
    GENERO VARCHAR2(20) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    TELEFONO_FIJO VARCHAR2(50),
    CELULAR VARCHAR2(50)NOT NULL,
    F_NACIMIENTO DATE NOT NULL,
    EMAIL VARCHAR2 (100)NOT NULL,
    DIRECCION VARCHAR2(100) NOT NULL,
    F_REGISTRO DATE NOT NULL
)TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX IDX_PK_ID_PACIENTE_PACIENTES
	ON PROYECTODB.TBL_PACIENTES(ID_PACIENTE)
	TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_PACIENTES 
    ADD CONSTRAINT PK_ID_PACIENTE_PACIENTES 
    PRIMARY KEY (ID_PACIENTE) USING INDEX IDX_PK_ID_PACIENTE_PACIENTES;

-----------------------------------------------------------------------------

CREATE TABLE PROYECTODB.TBL_INSUMOS
(
    ID_INSUMO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    CANT_DISPO NUMBER NOT NULL,
    UNI_MEDIDA VARCHAR2(50),
    ULT_ACTUALIZACION DATE NOT NULL
)TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX IDX_PK_ID_INSUMO_INSUMOS
	ON PROYECTODB.TBL_INSUMOS(ID_INSUMO)
	TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_INSUMOS 
    ADD CONSTRAINT PK_ID_INSUMO_INSUMOS
    PRIMARY KEY (ID_INSUMO) USING INDEX IDX_PK_ID_INSUMO_INSUMOS;

-----------------------------------------------------------------------------------

CREATE TABLE PROYECTODB.TBL_TRATAMIENTOS
(
    ID_TRATAMIENTO NUMBER NOT NULL,
    NOMBRE_TR VARCHAR2(50) NOT NULL,
    DESCRIPCION_TR VARCHAR2(500),
    COSTO_TR NUMBER NOT NULL,
    DURACION_ESTIMADA VARCHAR2(50) NOT NULL
)TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX IDX_PK_ID_TRATAMIENTO_TRATAMIENTOS
	ON PROYECTODB.TBL_TRATAMIENTOS(ID_TRATAMIENTO)
	TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_TRATAMIENTOS 
    ADD CONSTRAINT PK_ID_TRAMIENTO_TRATAMIENTOS
    PRIMARY KEY (ID_TRATAMIENTO) USING INDEX IDX_PK_ID_TRATAMIENTO_TRATAMIENTOS;

----------------------------------------------------------------------------------------

CREATE TABLE PROYECTODB.TBL_ESPECIALIDADES
(
    ID_ESPECIALIDAD NUMBER NOT NULL,
    NOMBRE_ESP VARCHAR2(100) NOT NULL,
    DESCRIPCION_ESP VARCHAR2(200)
)TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX IDX_PK_ID_ESPECIALIDAD_ESPECIALIDADES
	ON PROYECTODB.TBL_ESPECIALIDADES(ID_ESPECIALIDAD)
	TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_ESPECIALIDADES 
    ADD CONSTRAINT PK_ID_ESPECIALIDAD_ESPECIALIDADES
    PRIMARY KEY (ID_ESPECIALIDAD) USING INDEX IDX_PK_ID_ESPECIALIDAD_ESPECIALIDADES;

---------------------------------------------------------------------------------------------

CREATE TABLE PROYECTODB.TBL_ESTADO_CITAS
(
    ID_ESTADO NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL
)TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX IDX_PK_ID_ESTADO_ESTADO_CITAS
	ON PROYECTODB.TBL_ESTADO_CITAS(ID_ESTADO)
	TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_ESTADO_CITAS 
    ADD CONSTRAINT PK_ID_ESTADO_ESTADO_CITAS
    PRIMARY KEY (ID_ESTADO) USING INDEX IDX_PK_ID_ESTADO_ESTADO_CITAS;

-----------------------------------------------------------------------------------------------

CREATE TABLE PROYECTODB.TBL_ODONTOLOGOS
(
    ID_ODONTOLOGO NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    NOMBRES VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    NRO_LICENCIA NUMBER NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    TELEFONO NUMBER NOT NULL,
    F_INICIO DATE NOT NULL
)TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX IDX_PK_ID_ODONTOLOGO_ODONTOLOGOS
	ON PROYECTODB.TBL_ODONTOLOGOS(ID_ODONTOLOGO)
	TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_ODONTOLOGOS 
    ADD CONSTRAINT PK_ID_ODONTOLOGO_ODONTOLOGOS
    PRIMARY KEY (ID_ODONTOLOGO) USING INDEX IDX_PK_ID_ODONTOLOGO_ODONTOLOGOS;

---------------------------------------------------------------------------------------

CREATE TABLE PROYECTODB.TBL_CITAS
(
    ID_CITA NUMBER NOT NULL,
    MOTIVO VARCHAR2(500) NOT NULL,
    OBSERVACIONES VARCHAR2(500),
    F_CITA DATE NOT NULL,
    HORA_CITA VARCHAR2(10)NOT NULL,
    ID_ODONTOLOGO NUMBER NOT NULL,
    ID_PACIENTE NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL
)TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX IDX_PK_ID_CITA_CITAS
	ON PROYECTODB.TBL_CITAS(ID_CITA)
	TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_CITAS 
    ADD CONSTRAINT PK_ID_CITA_CITAS
    PRIMARY KEY (ID_CITA) USING INDEX IDX_PK_ID_CITA_CITAS;

ALTER TABLE PROYECTODB.TBL_CITAS ADD CONSTRAINT FK_CITAS_ESTADO_CITAS
	FOREIGN KEY (ID_ESTADO) REFERENCES PROYECTODB.TBL_ESTADO_CITAS(ID_ESTADO);

ALTER TABLE PROYECTODB.TBL_CITAS ADD CONSTRAINT FK_CITAS_ODONTOLOGOS FOREIGN KEY (ID_ODONTOLOGO) 
REFERENCES PROYECTODB.TBL_ODONTOLOGOS(ID_ODONTOLOGO);


ALTER TABLE PROYECTODB.TBL_CITAS ADD CONSTRAINT FK_CITAS_PACIENTES
    FOREIGN KEY (ID_PACIENTE) REFERENCES PROYECTODB.TBL_PACIENTES(ID_PACIENTE);

---------------------------------------------------------------------------------------

CREATE TABLE PROYECTODB.TBL_HISTORIAS_CLI (
    ID_HISTORIA NUMBER NOT NULL,
    ID_PACIENTE NUMBER NOT NULL,
    ID_CITA     NUMBER NOT NULL,
    DIAGNOSTICO VARCHAR2(500),
    F_REGISTRO  DATE NOT NULL
)
TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX IDX_PK_HIST_HISTORIAS_CLI 
  ON PROYECTODB.TBL_HISTORIAS_CLI (ID_HISTORIA)
  TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_HISTORIAS_CLI
  ADD CONSTRAINT PK_HIST_HISTORIAS_CLI
  PRIMARY KEY (ID_HISTORIA)
  USING INDEX IDX_PK_HIST_HISTORIAS_CLI;

ALTER TABLE PROYECTODB.TBL_HISTORIAS_CLI
  ADD CONSTRAINT FK_HISTORIAS_CLI_PACIENTES
  FOREIGN KEY (ID_PACIENTE)
    REFERENCES PROYECTODB.TBL_PACIENTES(ID_PACIENTE);

ALTER TABLE PROYECTODB.TBL_HISTORIAS_CLI
  ADD CONSTRAINT FK_HISTORIAS_CLI_CITAS
  FOREIGN KEY (ID_CITA)
    REFERENCES PROYECTODB.TBL_CITAS(ID_CITA);
-------------------------------------------------------------------------------------------------

CREATE TABLE PROYECTODB.TBL_DETALLE_ODONTOLOGOS
(
    ID_ODONTOLOGO NUMBER NOT NULL,
    ID_ESPECIALIDAD NUMBER NOT NULL
)TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX IDX_PK_ID_ODONTOLOGO_ID_ESPECIALIDAD_DETALLE_ODONTOLOGOS
	ON PROYECTODB.TBL_DETALLE_ODONTOLOGOS (ID_ODONTOLOGO,ID_ESPECIALIDAD)
	TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_DETALLE_ODONTOLOGOS ADD CONSTRAINT PK_ID_ODONTOLOGO_ID_ESPECIALIDAD_DETALLE_ODONTOLOGOS
    PRIMARY KEY (ID_ODONTOLOGO,ID_ESPECIALIDAD) USING INDEX IDX_PK_ID_ODONTOLOGO_ID_ESPECIALIDAD_DETALLE_ODONTOLOGOS;

ALTER TABLE PROYECTODB.TBL_DETALLE_ODONTOLOGOS ADD CONSTRAINT FK_DETALLE_ODONTOLOGOS_ODONTOLOGOS
	FOREIGN KEY (ID_ODONTOLOGO) REFERENCES PROYECTODB.TBL_ODONTOLOGOS(ID_ODONTOLOGO);
    
ALTER TABLE PROYECTODB.TBL_DETALLE_ODONTOLOGOS ADD CONSTRAINT FK_DETALLE_ODONTOLOGOS_ESPECIALIDADES
    FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES PROYECTODB.TBL_ESPECIALIDADES(ID_ESPECIALIDAD);

----------------------------------------------------------------------------------------------------------------

CREATE TABLE PROYECTODB.TBL_DETALLE_HCS 
(
    ID_DETALLE_HC NUMBER NOT NULL,
    ID_HISTORIA NUMBER NOT NULL,
    ID_TRATAMIENTO NUMBER NOT NULL
)TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX IDX_PK_ID_DETALLE_HC_DETALLE_HCS
	ON PROYECTODB.TBL_DETALLE_HCS (ID_DETALLE_HC)
	TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_DETALLE_HCS ADD CONSTRAINT PK_ID_DETALLE_HC_DETALLE_HCS
    PRIMARY KEY (ID_DETALLE_HC) USING INDEX IDX_PK_ID_DETALLE_HC_DETALLE_HCS;

---------------------------------------------------------------------------------------------------------------

CREATE TABLE PROYECTODB.TBL_DETALLE_INSUMOS 
(
    ID_DETALLE_INSUMO NUMBER NOT NULL,
    ID_INSUMO NUMBER NOT NULL,
    ID_DETALLE_HC NUMBER NOT NULL,	
    CANT_USADA NUMBER NOT NULL
)TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX IDX_PK_ID_DETALLE_INSUMO_DETALLE_INSUMOS
	ON PROYECTODB.TBL_DETALLE_INSUMOS (ID_DETALLE_INSUMO)
	TABLESPACE PROYECTODB_IDX;



ALTER TABLE PROYECTODB.TBL_DETALLE_INSUMOS ADD CONSTRAINT PK_ID_DETALLE_INSUMO_DETALLE_INSUMOS
    PRIMARY KEY (ID_DETALLE_INSUMO) USING INDEX IDX_PK_ID_DETALLE_INSUMO_DETALLE_INSUMOS;

ALTER TABLE PROYECTODB.TBL_DETALLE_INSUMOS ADD CONSTRAINT FK_DETALLE_INSUMOS_DETALLE_HCS 
FOREIGN KEY (ID_DETALLE_HC) REFERENCES PROYECTODB.TBL_DETALLE_HCS (ID_DETALLE_HC);


ALTER TABLE PROYECTODB.TBL_DETALLE_INSUMOS ADD CONSTRAINT FK_DETALLE_INSUMOS_INSUMOS 
FOREIGN KEY (ID_INSUMO) REFERENCES PROYECTODB.TBL_INSUMOS (ID_INSUMO);
---------------------------------------------------------------------------------------------------------------


ALTER TABLE PROYECTODB.TBL_DETALLE_HCS ADD CONSTRAINT FK_DETALLE_HCS_TRATAMIENTOS
FOREIGN KEY(ID_TRATAMIENTO) REFERENCES PROYECTODB.TBL_TRATAMIENTOS(ID_TRATAMIENTO)

ALTER TABLE PROYECTODB.TBL_DETALLE_HCS ADD CONSTRAINT FK_DETALLE_HCS_HISTORIAS_CLI
FOREIGN KEY(ID_HISTORIA) REFERENCES PROYECTODB.TBL_HISTORIAS_CLI(ID_HISTORIA)

